version: '3'

services:
  db:
    image: postgres:9.5-alpine
    environment: 
      POSTGRES_DB: pollsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/django-blog
    ports:
      - "8000:8000"
    depends_on: 
      - db

volumes:
  postgres_data:
